[package]
name = "fanotify-fid"
version = "0.2.4"
edition = "2024"
license = "MIT"
description = "Linux fanotify FID (File Identifier) mode event parser and file handle utilities"
documentation = "https://docs.rs/fanotify-fid"
repository = "https://github.com/lenitain/fanotify-fid"
readme = "README.md"
keywords = ["filesystem", "syscall", "linux", "fanotify"]
categories = ["os::linux-apis", "filesystem"]
authors = ["lenitain <xt.zhu@qq.com>"]

include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/",
    "tests/"
]

[lib]
name = "fanotify_fid"
path = "src/lib.rs"

[dependencies]
libc = "0.2"
smallvec = { version = "1", features = ["const_generics"] }

[dev-dependencies]
tempfile = "3"
